### ISSUE TITLE
Editor freezes when inputting the question mark

### ISSUE THREAD

**Issue by kuige** [cheminfo/openchemlib-js#117]
In some situations, the asterisk(*) is needed to be used as a separator among the SMILES, just like marvinjs did.

But OpenChemLib doesn't have the asterisk mark, so I want to use the question mark instead.

The question mark：

<img width="61" alt="image" src="https://user-images.githubusercontent.com/8212800/131317850-96cfb074-f97b-4207-9e47-83e34e3c1dd0.png">

However, when adding a question mark the the molecule, the editor and the whole page get stuck and become unresponsive , after checking the chrome DevTools ,  it seems that the editor go to an endless loop.

![openchemlib_editor_freezes](https://user-images.githubusercontent.com/8212800/131319392-a6e18580-7b4c-45e7-8994-df33faf58fe0.gif)

**Comment by lpatiny** [comment]
Do you have a testcase to share ? In our testcases (example / editor) it works correctly.

![image](https://user-images.githubusercontent.com/1484241/131688527-8bb9c871-8614-4309-b18c-af0288a1f79e.png)


A dialog is opened and apparently hidden by OCL editor and you should see it in the DOM.

**Comment by targos** [comment]
I suspect that you are rendering the editor in an element that is displayed in front of the dialog.
It happened in one of our applications and we fixed it by defining a z-index on the dialog box class:

```css
.gwt-DialogBox {
  z-index: 50;
}
```

**Comment by kuige** [comment]
Yes, it's the issue of dialog, after moving the editor out of dialog, it works as expected. 👍

**Comment by kuige** [comment]
<img width="277" alt="image" src="https://user-images.githubusercontent.com/8212800/131776337-755c920c-50aa-4b0b-98da-5e1f5c3f3b9c.png">
But the question mark isn't the feature I expected.<br/><br/>
At first, I think the question mark is the same as asterisk(*), just like marvinjs did.<br/>

[https://marvinjs-demo.chemaxon.com/latest/](https://marvinjs-demo.chemaxon.com/latest/)

<img width="902" alt="image" src="https://user-images.githubusercontent.com/8212800/131777858-fbe73bb4-5947-494e-9e77-176305be544d.png">

But it isn't.

Is it possible to add this feature in OpenChemLib editor ? @lpatiny @targos

**Comment by lpatiny** [comment]
openchemlib is chemistry aware and if you draw an exact structure it has to correspond to something realistic.

If you want you may activate the fragment option to activate the query features and allow any atom

https://cheminfo.github.io/openchemlib-js/classes/StructureEditor.html

**Comment by kuige** [comment]
I call the `setFragment` method, but still cannot input the asterisk mark(*).

Could you explain more detail ? thanks

**Comment by lpatiny** [comment]
If you press `q` when hover an atom you can specify 'any atom'.

![image](https://user-images.githubusercontent.com/1484241/131970926-07dc1719-e385-4984-a56d-bcd14a4c1f59.png)

**Comment by kuige** [comment]
<img width="349" alt="image" src="https://user-images.githubusercontent.com/8212800/131972295-b1302a88-b6de-431a-92f2-a80202ca2fc5.png">

After checking the "any atomic number" option, I can input the question mark, but the generated SMILES doesn't include the question mark.

**Comment by lpatiny** [comment]
We don't support query features in 'SMILES' but you can use the molfile.
